name: Amazon Bot - Monitoreo

on:
  schedule:
    - cron: "*/5 * * * *"  # Ejecuta cada 5 minutos
  workflow_dispatch:        # Permite ejecución manual

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # ✅ Asegura versión correcta

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar bot Amazon
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot_amazon.py
